# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

services:
  pygeoapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # if we are running pygeoapi via the dockerfile
      # we should assume that jaeger is also running in the compose network
      - COLLECTOR_ENDPOINT=jaeger
      - COLLECTOR_GRPC_PORT=4317
    env_file:
      - .env
    ports:
      - 5000:80
    depends_on:
      database:
        condition: service_healthy
      mysql:
        condition: service_healthy

  database:
    image: postgis/postgis:14-3.2-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./tests/data/postgres/:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 8s
      retries: 5

  mysql:
    image: mysql:8
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./tests/data/mysql/:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h $MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD --silent",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      # Ports defined here https://www.jaegertracing.io/docs/next-release/getting-started/#all-in-one
      - "16686:16686" # expose the UI
      - "4317:4317" # expose the OTLP HTTP port
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    profiles:
      - tracing
